import type { NextPage } from 'next';
import Head from 'next/head';
import { Home as HomeComponent } from 'components/Home';
import { apolloClient } from 'utils';
import * as Types from '__generated__';

interface Props {
  conversations: Types.TGetConversation[];
  errors?: any;
}
const Home: NextPage<Props> = ({ conversations }) => {
  return (
    <div>
      <Head>
        <title>Home | ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-c.png" />
      </Head>
      <HomeComponent conversations={conversations} />
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  try {
    const client = apolloClient();
    const res = await client.query<Types.TGetConversationResponse>({
      query: Types.GET_ALL_CONVERSATION,
    });

    return {
      props: {
        conversations: res.data.getConversations.data,
      },
    };
  } catch (error: any) {
    return {
      props: {
        errors: error,
      },
    };
  }
};
