import type { NextPage } from 'next';
import Head from 'next/head';
import { Home as HomeComponent } from 'components/Home';
import { apolloClient } from 'utils';
import * as Types from '__generated__';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home | ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-c.png" />
      </Head>
      <HomeComponent />
    </div>
  );
};

export default Home;

export const getStaticProps = async () => {
  // const res = await apolloClient().query<Types.TGetConversationResponse>({
  //   query: Types.GET_ALL_CONVERSATION,
  // });

  // console.log('res', res.errors);

  return {
    props: {
      conversations: 'hello'
    }
  }
};
