import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Auth } from '../components/Auth';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-c.png" />
      </Head>
      <main className="w-full ">
        <div className="m-auto mt-10 w-16">
          <Image
            src={'/logo.png'}
            layout="responsive"
            width={75}
            height={75}
            alt="logo"
          />
        </div>
        <Auth />
      </main>
    </div>
  );
};

export default Home;
